USE IG_CLONE;

SELECT 
    *
FROM
    USERS
ORDER BY USERS.CREATED_AT ASC
LIMIT 5;

SELECT 
    *
FROM
    USERS
WHERE
    USERS.ID NOT IN (SELECT 
            PHOTOS.USER_ID
        FROM
            PHOTOS);
            
SELECT 
    U.USERNAME, 
    P.ID AS PHOTO_ID, 
    COUNT(L.USER_ID) AS TOTAL_LIKES
FROM 
    USERS U
JOIN 
    PHOTOS P ON U.ID = P.USER_ID
JOIN 
    LIKES L ON P.ID = L.PHOTO_ID
GROUP BY 
    P.ID, U.USERNAME
ORDER BY 
    TOTAL_LIKES DESC
LIMIT 1;

SELECT 
    tag_id, tag_name,COUNT(tag_id) total_count
FROM
    photo_tags,
    tags
WHERE
    id = tag_id
GROUP BY tag_id
ORDER BY total_count DESC
LIMIT 5;

SELECT 
    DAYNAME(CREATED_AT) AS DAY_OF_WEEK, 
    COUNT(*) AS USER_COUNT
FROM 
    USERS
GROUP BY 
    DAY_OF_WEEK
ORDER BY 
    USER_COUNT DESC;
    
        
SELECT 
    COUNT(P.ID) / COUNT(DISTINCT (P.USER_ID)) AS AVG_POST_PER_USER
FROM
    PHOTOS P;
SELECT 
    COUNT(P.ID) / COUNT(U.ID) AS TOTAL_PHOTOS_DIV_TOTAL_USERS
FROM
    PHOTOS P
        RIGHT JOIN
    USERS U ON U.ID = P.USER_ID;
    
SELECT
    USER_ID
FROM 
    LIKES
GROUP BY 
    USER_ID
HAVING 
    COUNT(PHOTO_ID) = (SELECT COUNT(ID) FROM PHOTOS);
